server {

    listen 80 default_server;
    listen [::]:80 default_server;
    #server_name;
    
    client_max_body_size        10m;

    root /var/www;
    index index.php index.html index.htm default.html default.htm;

    location / {
        autoindex on;
    }

    # location / {
    #     try_files $uri $uri/ index.php =404;
    # }

}
