name: Build only

on:
  workflow_dispatch:
    inputs:
      source_ref:
        description: "tag, branch, or commit SHA to build. (Optional)"
        type: string
        required: false
        default: ""

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/_reusable_workflow.yaml
    with:
      source_ref: ${{ inputs.source_ref }}
      do_install: false
      upload_artifacts: false
