name: Build+Package[+Upload]

on:
  workflow_dispatch:
    inputs:
      upload_artifacts:
        description: "Upload artifacts"
        required: true
        default: false
        type: boolean

jobs:
  package:
    uses: ./.github/workflows/_reusable_workflow.yaml
    with:
      do_install: true
      upload_artifacts: ${{ inputs.upload_artifacts }}
